"""
Generator for the staged pretraining sweep configs under configs/pretrain/real_runs/.

Regenerates all four stages from the WINNER constants below. To progress from one
stage to the next with a real result instead of a placeholder assumption, edit the
relevant *_WINNER constant to match what actually won the previous stage (by
pretraining val loss or by outputs/pretrain/real_runs/<stage>/<run>/finetune_summary.md),
then rerun this script:

    python configs/pretrain/real_runs/generate_sweep_configs.py

This overwrites the stage*_*.yaml and stage*_config_list.txt files in this directory.
Stage 1 configs are not regenerated by this script (its axis, norm_strategy/num_bins,
has no upstream "winner" to depend on) -- edit stage1_norm_*.yaml directly if needed.
"""
import copy
import os

from omegaconf import OmegaConf

REAL_RUNS_DIR = os.path.dirname(os.path.abspath(__file__))

# ---- Base template shared by every generated config (mirrors stage1_norm_binary.yaml) ----
BASE = {
    "paths": {
        "output_dir": None,  # filled per-config
        "model_config_path": "${paths.output_dir}/model_config.json",
        "ann_table_path": "/scratch/kchen13/hmc_final_fixed/pretrain.h5ad",
    },
    "checkpoint_path": None,
    "wandb": {
        "enabled": True,
        "entity": "haoze-deng-university-of-toronto",
        "project": None,  # filled per-stage
        "run_name": None,  # filled per-config
        "run_notes": None,  # filled per-config
    },
    "training": {
        "seed": 42,
        "init_lr": 1e-3,
        "batch_size": 64,
        "max_epochs": 200,
        "cosine_warmup_ratio_or_step": 0.1,
        "log_interval": 10,
        "patience": 20,
        "grad_accumulation_steps": 1,
        "enable_fp16": False,
        "notes": None,  # filled per-config
        "tasks": ["masking"],
        "masking_prob": 0.15,
        "masking_taxa_prob": 0.15,
        "optimizer": "adamw",
        "lr_scheduler": "cosine",
        "grad_clip": 1.0,
        "checkpoint_every": 5,
        "finetune_mode": "none",
        "w_masking_from_cls": 1.0,
        "w_masking_taxa": 1.0,
    },
    "validation": {
        "batch_size": 64,
        "eval_interval_epochs": 1,
    },
    "data": {
        "norm_strategy": "binning",
        "num_bins": 10,
        "split_key": "study_id",
        "val_size": 0.1,
        "use_batch_labels": True,
        "max_seq_len": 200,
        "num_workers": 4,
        "metadata_fields": [],
    },
    "model": {
        "params": {
            "d_model": 128,
            "nhead": 8,
            "d_hid": 512,
            "nlayers": 3,
            "dropout": 0.1,
            "abundance_emb_style": "continuous",
            "use_gnn": False,
            "sample_emb_style": "cls",
            "preinitialized_taxa_embedding_path": None,
            "freeze_preinitialized_embeddings": False,
            "preinitialized_embedding_projection": "linear",
        }
    },
    "debug": {
        "nrows": None,
        "start_over": True,
    },
    "finetune": {
        "paths": {
            "downstream_train": "/scratch/kchen13/hmc_final_fixed/downstream_train.h5ad",
            "downstream_test": "/scratch/kchen13/hmc_final_fixed/downstream_test.h5ad",
        },
        "training": {
            "init_lr": 1e-4,
            "max_epochs": 10,
            "patience": 10,
            "finetune_mode": "partial",
            "batch_size": 64,
            "use_class_weights": True,
        },
        "val_size": 0.2,
    },
}

# ---- Carry-forward winners: EDIT THESE once a stage's real results are in, then rerun ----
STAGE1_WINNER = {"norm_strategy": "log_rel_abundance", "num_bins": 10}  # num_bins unused (non-binning strategy); Stage 1 winner picked from outputs/pretrain/real_runs/stage1/stage1_*/finetune_summary.md
STAGE2_WINNER = {"tasks": ["masking_taxa"], "masking_prob": 0.3}  # Stage 2 winner picked from outputs/pretrain/real_runs/stage2/stage2_finetune_summary_combined.md: best aggregate rank across accuracy/F1-macro/AUROC, no majority-class collapse, avoids the "combined" family's task-interference issue
STAGE3_WINNER = {"sample_emb_style": "cls", "abundance_emb_style": "concatenation", "use_batch_labels": True}  # Stage 3 winner picked from outputs/pretrain/real_runs/stage3/stage3_finetune_summary_combined.md: best aggregate rank across accuracy/F1-macro/AUROC (best AUROC, 2nd-best F1, no majority-class collapse)


def make_config(name, stage, notes, overrides_training=None, overrides_data=None, overrides_model=None):
    cfg = copy.deepcopy(BASE)
    cfg["paths"]["output_dir"] = f"outputs/pretrain/real_runs/{stage}/{name}"
    cfg["wandb"]["project"] = f"microbiome-pretrain-sweep-{stage}"
    cfg["wandb"]["run_name"] = name
    cfg["wandb"]["run_notes"] = notes
    cfg["training"]["notes"] = notes

    cfg["data"]["norm_strategy"] = STAGE1_WINNER["norm_strategy"]
    cfg["data"]["num_bins"] = STAGE1_WINNER["num_bins"]
    if overrides_data:
        cfg["data"].update(overrides_data)

    if overrides_training:
        cfg["training"].update(overrides_training)

    if overrides_model:
        cfg["model"]["params"].update(overrides_model)

    return cfg


def write_config(cfg, filename):
    path = os.path.join(REAL_RUNS_DIR, filename)
    OmegaConf.save(OmegaConf.create(cfg), path)
    return path


def write_list(paths, filename):
    path = os.path.join(REAL_RUNS_DIR, filename)
    with open(path, "w") as f:
        for p in paths:
            f.write(f"configs/pretrain/real_runs/{p}\n")
    return path


def generate_stage2():
    task_variants = [
        ("masking", ["masking"]),
        ("masking_from_cls", ["masking_from_cls"]),
        ("masking_taxa", ["masking_taxa"]),
        ("combined", ["masking", "masking_from_cls", "masking_taxa"]),
    ]
    mask_probs = [0.3, 0.5, 0.8]

    files = []
    for task_slug, tasks in task_variants:
        for mp in mask_probs:
            mask_slug = f"mask{int(mp * 100):03d}"
            name = f"stage2_{task_slug}_{mask_slug}"
            notes = f"Stage 2 sweep: tasks={tasks}, masking_prob={mp} (on assumed Stage 1 winner: {STAGE1_WINNER})"
            cfg = make_config(name, "stage2", notes, overrides_training={"tasks": tasks, "masking_prob": mp})
            filename = f"{name}.yaml"
            write_config(cfg, filename)
            files.append(filename)
    write_list(files, "stage2_config_list.txt")
    print(f"Stage 2: wrote {len(files)} configs")


def generate_stage3():
    files = []

    baseline_name = "stage3_baseline"
    baseline_notes = (
        f"Stage 3 baseline: sample_emb_style=cls, abundance_emb_style=continuous, "
        f"use_batch_labels=true (on assumed Stage 1/2 winners: {STAGE1_WINNER}, {STAGE2_WINNER})"
    )
    cfg = make_config(
        baseline_name, "stage3", baseline_notes,
        overrides_training={"tasks": STAGE2_WINNER["tasks"], "masking_prob": STAGE2_WINNER["masking_prob"]},
        overrides_data={"use_batch_labels": STAGE3_WINNER["use_batch_labels"]},
        overrides_model={"sample_emb_style": STAGE3_WINNER["sample_emb_style"],
                          "abundance_emb_style": STAGE3_WINNER["abundance_emb_style"]},
    )
    write_config(cfg, f"{baseline_name}.yaml")
    files.append(f"{baseline_name}.yaml")

    variants = [
        ("stage3_sample_emb_avgpool", {"sample_emb_style": "avg-pool"}, {}),
        ("stage3_abundance_emb_scaling", {"abundance_emb_style": "scaling"}, {}),
        ("stage3_abundance_emb_concatenation", {"abundance_emb_style": "concatenation"}, {}),
        ("stage3_no_batch_labels", {}, {"use_batch_labels": False}),
    ]
    for name, model_over, data_over in variants:
        model_overrides = {"sample_emb_style": STAGE3_WINNER["sample_emb_style"],
                            "abundance_emb_style": STAGE3_WINNER["abundance_emb_style"]}
        model_overrides.update(model_over)
        data_overrides = {"use_batch_labels": STAGE3_WINNER["use_batch_labels"]}
        data_overrides.update(data_over)
        notes = f"Stage 3 sweep: {name} (baseline + this one change; see {baseline_name} for the reference)"
        cfg = make_config(
            name, "stage3", notes,
            overrides_training={"tasks": STAGE2_WINNER["tasks"], "masking_prob": STAGE2_WINNER["masking_prob"]},
            overrides_data=data_overrides,
            overrides_model=model_overrides,
        )
        write_config(cfg, f"{name}.yaml")
        files.append(f"{name}.yaml")

    write_list(files, "stage3_config_list.txt")
    print(f"Stage 3: wrote {len(files)} configs")


def generate_stage4():
    bins_values = [5, 10, 20]
    mask_probs = [0.3, 0.5, 0.8]
    files = []
    for bins in bins_values:
        for mp in mask_probs:
            mask_slug = f"mask{int(mp * 100):03d}"
            name = f"stage4_bins{bins}_{mask_slug}"
            notes = (
                f"Stage 4 fine sweep: num_bins={bins}, masking_prob={mp} "
                f"(on assumed Stage 3 winner architecture: {STAGE3_WINNER}, Stage 2 tasks: {STAGE2_WINNER['tasks']})"
            )
            cfg = make_config(
                name, "stage4", notes,
                overrides_training={"tasks": STAGE2_WINNER["tasks"], "masking_prob": mp},
                overrides_data={"norm_strategy": "binning", "num_bins": bins,
                                 "use_batch_labels": STAGE3_WINNER["use_batch_labels"]},
                overrides_model={"sample_emb_style": STAGE3_WINNER["sample_emb_style"],
                                  "abundance_emb_style": STAGE3_WINNER["abundance_emb_style"]},
            )
            write_config(cfg, f"{name}.yaml")
            files.append(f"{name}.yaml")
    write_list(files, "stage4_config_list.txt")
    print(f"Stage 4: wrote {len(files)} configs")


if __name__ == "__main__":
    generate_stage2()
    generate_stage3()
    generate_stage4()
