paths:
  output_top_level: "./outputs/contrastive_refactored_multinomial_downsample_clr"
  model_config_path: "${paths.output_top_level}/model_config.json"
  ann_table_path: "/project/aip-rahulgk/gutmodel/hmc_final/pretrain.h5ad"
  vocab_path: null
  best_dir: "${paths.output_top_level}/best_model/"
  checkpoint_dir: "${paths.output_top_level}/checkpoints/"
  data_restore_dir: "${paths.output_top_level}/data_cache/"
  intermediate_dir: "${paths.output_top_level}/intermediate/"

wandb:
  enabled: true
  entity: "haoze-deng-university-of-toronto"
  project: "microbiome-foundation"
  run_name: multinomial_downsample_clr_denoising
  run_notes: null

training:
  seed: 423985693
  init_lr: 1e-4
  batch_size: 64
  max_epochs: 50 # for testing
  cosine_warmup_ratio_or_step: 0.1 # is this ever used?
  log_interval: 10
  patience: null
  grad_accumulation_steps: 1
  enable_fp16: false
  train_mask_ratio: 0.15
  notes: "Testing denoising after refactor"
  tasks: ["denoising"]
  contrastive_temperature: 0.2

validation:
  batch_size: 128
  eval_interval_epochs: 1

data:
  norm_strategy: "clr" # choices: clr, none, rel_abundance, log_rel_abundance, log_counts, binning, arcsine
  split_key: "study_id" # we probably want to split train/val by entire studies, so it resembles close to real-world/test scenario
  val_size: 0.1
  use_batch_labels: false
  max_seq_len: 500
  num_workers: 4
  distribution: "multinomial"

model:
  use_gnn: false
  
  tasks:
    do_mvc: false
    do_taxa_decoder: false
    do_contrastive: false

  # === FLEXIBLE ARCHITECTURE SECTION ===
  # Any key added here is automatically passed to the model config dict
  params:
    d_model: 128
    d_proj: 128
    nhead: 8
    d_hid: 512
    nlayers: 3
    dropout: 0.1
    abundance_emb_style: "continuous" # choices: scaling, continuous, category
    # freeze_vocab: false
    # freeze_value_encoder: false
    # do_attn_mask: false
    # Example: If you change architecture, just add new keys here
    # activation: "gelu" 
    # use_flash_attn: true

debug:
  nrows: null
  start_over: false