paths:
  output_dir: "outputs/pretrain"
  model_config_path: "outputs/pretrain/model_config.json"
  ann_table_path: "/project/6101781/gutmodel/hmc_final/pretrain.h5ad"

wandb:
  enabled: false
  entity: "haoze-deng-university-of-toronto"
  project: "microbiome-foundation"
  run_name: first_run
  run_notes: null

training:
  seed: 42
  init_lr: 1e-4
  batch_size: 32
  max_epochs: 15
  cosine_warmup_ratio_or_step: 0.1
  log_interval: 10
  patience: null
  grad_accumulation_steps: 1
  enable_fp16: false
  train_mask_ratio: 0.15
  notes: "Experimenting with new architecture"
  tasks: ["denoising"]
  contrastive_temperature: 0.2
  masking_prob: 0.15

validation:
  batch_size: 64
  eval_interval_epochs: 1

data:
  norm_strategy: "clr" # choices: clr, none
  split_key: "study_id" # we probably want to split train/val by entire studies, so it resembles close to real-world/test scenario
  val_size: 0.1
  use_batch_labels: true
  max_seq_len: 200
  num_workers: 4
  downsample_distribution: "zinb"


model:  
  tasks:
    do_mvc: false
    do_taxa_decoder: false
    do_contrastive: false

  # === FLEXIBLE ARCHITECTURE SECTION ===
  # Any key added here is automatically passed to the model config dict
  params:
    d_model: 128
    nhead: 8
    d_hid: 512
    nlayers: 3
    dropout: 0.1
    abundance_emb_style: "continuous" # choices: scaling, continuous, category
    use_gnn: false
    # Example: If you change architecture, just add new keys here
    # activation: "gelu" 
    # use_flash_attn: true
    model_distribution: "zinb" # choices: zinb,...

debug:
  nrows: 200
  start_over: true