paths:
  output_dir: "outputs/eval_pathway"
  pretrained_model_dir: "outputs/pretrain"
  checkpoint_path: "outputs/pretrain_mask_gnn/best_model/best_model/model.safetensors"
  eval_files: 
    - "/home/kchen/microbiome/gut_microbiome_GPT/data/conference/pathway.h5ad"

eval:
  seed: 42
  overwrite_output_dir: true
  embedding_type: "cls" # choices: cls, mean, sum
  return_full_output: true # whether to return the full output of the model (e.g. for probing) or just the embeddings (for downstream tasks)
  save_embeddings: false
  save_metadata: true
  tasks: ['masking']
  eval_on_downstream_tasks: false  
  with_model: True

data:
  batch_size: 64
  norm_strategy: "clr" # choices: clr, none
  split_key: "study_id" # we probably want to split train/val by entire studies, so it resembles close to real-world/test scenario
  use_batch_labels: false
  max_seq_len: 200
  num_workers: 4
  downsample_distribution: "zinb"

model:
  # === FLEXIBLE ARCHITECTURE SECTION ===
  # Any key added here is automatically passed to the model config dict
  params:
    d_model: 128
    nhead: 8
    d_hid: 512
    nlayers: 3
    dropout: 0.1
    abundance_emb_style: "continuous" # choices: scaling, continuous, category
    # Example: If you change architecture, just add new keys here
    # activation: "gelu" 
    # use_flash_attn: true
    model_distribution: "zinb" # choices: zinb,...
    use_gnn: true

# optional, if you want to specify downstream tasks
downstream_tasks_config:
  methods:
    xgboost:
      search_type: "none"
  tasks:
    age:
      label_type: "continuous_label"
      ignored_labels: []
      target_col: "downstream_task"
    bmi:
      label_type: "continuous_label"
      ignored_labels: []
      target_col: "downstream_task"
    sex:
      label_type: "categorical_label"
      ignored_labels: []
      target_col: "downstream_task"
    supplement:
      label_type: "categorical_label"
      ignored_labels: []
      target_col: "downstream_task"
    helicobacter_pylori_infection:
      label_type: "categorical_label"
      ignored_labels: []
      target_col: "downstream_task"
    hbv_infection:
      label_type: "categorical_label"
      ignored_labels: []
      target_col: "downstream_task"
    hiv_infection:
      label_type: "categorical_label"
      ignored_labels: []
      target_col: "downstream_task"
    sunflower_seed_oil_emollient_therapy:
      label_type: "categorical_label"
      ignored_labels: ['extraction_control']
      target_col: "downstream_task"
    chemotherapy:
      label_type: "categorical_label"
      ignored_labels: []
      target_col: "downstream_task"
    type_1_diabetes:
      label_type: "categorical_label"
      ignored_labels: []
      target_col: "downstream_task"
    crohns_disease:
      label_type: "categorical_label"
      ignored_labels: []
      target_col: "downstream_task"
    diarrhea:
      label_type: "categorical_label"
      ignored_labels: []
      target_col: "downstream_task"
    location:
      label_type: "categorical_label"
      ignored_labels: []
      target_col: "downstream_task"
  


